title: The Gen Z Catechism
description: 60 social-media style posts to train up the next generation in the Word of God.
url: "" # set your custom domain here if using one
baseurl: "" # for project pages, set to "/<repo>"

# Plugins (all supported by GitHub Pages)
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Pretty URLs for pages (e.g., /chapters/post-01/)
permalink: pretty

# Exclude non-site files from the build
exclude:
  - gen-z-catechism.pdf
