title: The Gen Z Catechism
description: 60 social-media style posts to train up the next generation in the Word of God.
# Production URL and baseurl for GitHub Project Pages
url: "https://hmeng.github.io" # set to your GitHub Pages user/org URL
baseurl: "/the-gen-z-catechism" # repo name; leave blank if using a custom domain

# Plugins (all supported by GitHub Pages)
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Pretty URLs for pages (e.g., /chapters/post-01/)
permalink: pretty

# Exclude non-site files from the build
exclude:
  - gen-z-catechism.pdf
